fixes #72, added tests
gfscott/eleventy-plugin-youtube-embed pull request #73
Opened 2022-03-12 21:09 UTC by christopherpickering

Hi,
I added the option for two additional YouTube url params:

- option to only recommend videos from the same channel
- option to reduce YouTube branding

I moved the url params into their own function to make it easier for others to add more as needed.

Thanks!

2022-03-12 22:03 UTC, christopherpickering commented
Sorry for so many commits...

2022-03-15 23:40 UTC, gfscott requested changes
🎉 Thanks so much for contributing this! Really appreciate the hard work you've put in.

Just a few minor stylistic tweaks to propose below, and I'd like to change one of the option names you added. But otherwise this is looking great. Let me know if you have questions or need any help finishing up! Looking forward to merging this.

2022-03-15 23:40 UTC, gfscott commented on lib/buildEmbed.js
> +  return params.join("&")
- Any reason for returning `!1` instead of just `false`?
- Do we need to return anything? We could leave it and the assignment remains `undefined`.
- Just to be on the safe side I'd like to join the params with `&amp;`

```suggestion
if(params.length > 0) {
  return params.join("&amp;")
}
```

2022-03-15 23:40 UTC, gfscott commented on lib/buildEmbed.js
> +  if(options.recommendChannel) params.push('rel=0');
I'd like to tweak the name of this option handle to make it more obviously a boolean choice...

```suggestion
  if(options.recommendSelfOnly) params.push('rel=0');
```

2022-03-15 23:40 UTC, gfscott commented on README.md
> +      <td><code>recommendChannel</code></td>
See option rename below!

```suggestion
      <td><code>recommendSelfOnly</code></td>
```

2022-03-15 23:40 UTC, gfscott commented on lib/buildEmbed.js
> +  out += params ? ` params="` + params + `"`: "";
I think it's easier to read this when using template literals!

```suggestion
  out += params ? ` params=${params}`: "";
```

2022-03-15 23:40 UTC, gfscott commented on lib/buildEmbed.js
> +  out += params ? "?" + params : "";
Same thing with template literals here.

```suggestion
  out += params ? `?${params}` : "";
```

2022-03-15 23:40 UTC, gfscott commented on README.md
> +      <td><code>modestBranding</code></td>
TIL this param existed! Love it 💯

2022-03-15 23:40 UTC, gfscott commented on test.js
> +
🙏🏻 Thank you for being so thorough with writing these tests!

2022-03-16 13:12 UTC, christopherpickering commented on lib/buildEmbed.js
> +  out += params ? ` params="` + params + `"`: "";
even better :)

2022-03-16 13:19 UTC, christopherpickering commented
Thanks! So changing the & to &amp; and removing quotes will be ok? I'm updating the tests for this and then should be good.
```
<lite-youtube ...  params=autoplay=1&amp;rel=0&amp;modestbranding=1>
```

2022-03-16 13:25 UTC, christopherpickering commented
I've added the quotes back to the YouTube-lite param string (I think that is correct?) and passed the tests w/ the new param name. I think it is good to go.

2022-03-21 23:00 UTC, gfscott approved these changes
🎖️ Thanks again! Really happy to have these new options available.

2022-03-21 23:01 UTC, merged

2022-03-22 01:43 UTC, christopherpickering commented
nice! thanks!